- [[Diagnostic Criteria]]
	- Consensus document of the Barany Society and the International Headache Society [Vestibular Migraine Diagnostic Criteria.pdf](../assets/Vestibular_Migraine_Diagnostic_Criteria_1639521076649_0.pdf) [Lempert, J Vestib Res 2012]
		- current or previous migraine with or without aura
		- ≥5 episodes of vestibular symptoms of moderate or severe intensity
		- Each episode lasting 5 minute  to 72 hours
		- at least 50% of these episodes involve ≥1 migrainous symptom(headache, photophobia & phonophobia, or visual aura)
		- No other explanation